### ISSUE TITLE
cydia and ssh don't work

### ISSUE THREAD

**Issue by wangliangliang2** [thisiswisy/g0blin#2]
g0blin show me that I have jailbreaked, but I can't use ssh and cydia will crash when open it

**Comment by thisiswisy** [comment]
Does g0blin say: "please open cydia"?

**Comment by wangliangliang2** [comment]
yes，it does.
fly:then after  I try https://github.com/thisiswisy/v0rtex-injector/ this tool ,then it can use ssh with g0blin but cydia still can't work.  
then I done a stupid thing that  cd /Application then rm -r Cydia.app 
so I want to ask you a question : how can I force g0blin to reinstall Cydia .😂

**Comment by GitGhoster** [comment]
I am having the same problem. I downloaded the IPA from this link [https://yalujailbreak.net/g0blin-jailbreak/ ](url)

**Comment by thisiswisy** [comment]
Thanks for testing that!
